### ISSUE TITLE
NGMLR

### ISSUE THREAD

**Issue by shimbalama** [friend1ws/nanomonsv#2]
HI 

All our bams are mapped with NGMLR and while we are excited to use your tool, we're not excited about re-mapping everything with minimap2 and certainly don't want to have to keep 2 copies of all bams in the long run. 

I tried running parse.py on our bams but hit these errors:

```
if query_strand == '+' and query_end != query_pos_cur:
            import pdb; pdb.set_trace()
            print("query end inconsistent!!")
            sys.exit(1)
        if query_strand == '-' and query_start != query_pos_cur + 1:
            import pdb; pdb.set_trace()
            print("query end inconsistent!!")
            sys.exit(1)
```

Is that caused by not using minimap2 to map?

Thanks in advance

**Comment by friend1ws** [comment]
Hi, thank you very much for your interest in our software.
I tried on our BAM file aligned with NGMLR and got the same error.
So this is probably because of NGMLR.

At the same time, these lines are inserted mainly for debugging (check the consistency of CIGAR string),
and the software may work without this... 
So I will try to first check whether making our software compatible with NGMLR is easy or not.

**Comment by shimbalama** [comment]
Thanks!

**Comment by shimbalama** [comment]
Hi again,

Do you have a timeline on this?

**Comment by friend1ws** [comment]
Hi,

Sorry for the late response. Now I'm investing the BAM file produced by NGMLR.
With slight modifications, nanomonsv may be able to accept NGMLR format files. 
Please wait for an additional several days for the conclusion.

**Comment by friend1ws** [comment]
Hi, 

Now I think version 0.1.2 nanomonsv can accept BAM file by NGMLR. I tested using my own data (3 paired nanopore data). So I'm happy if you could try it.

**Comment by shimbalama** [comment]
Thanks, I will.
