### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by willhooper** [friend1ws/nanomonsv#38]
Hi, 

Thanks for developing this great tool! It seems like nanomonsv doesn't currently support CRAM input. Would it be possible to add this? I think many would find this useful. 

Thanks!
Will

**Comment by friend1ws** [comment]
Hi, thank you very much for your interest in our software.
Supporting CRAM is an option. But I'm still not sure whether people often use CRAM format for Nanopore sequence data or not so.

Supporting CRAM is technically not very challenging, But the challenge for supporting CRAM input is that we use random access in the validation phase, and the computational cost may increase significantly. 
I will try to optimize Nanomonsv so that in near future we may accept CRAM format.

**Comment by willhooper** [comment]
Thank you! We use CRAM for our nanopore data stored in the cloud to save on storage costs, I suspect anyone else working in the cloud would find this useful as well.

**Comment by friend1ws** [comment]
OK, I will support CRAM format and try to release it in the next version.

**Comment by friend1ws** [comment]
We have almost finished the CRAM support in the devel branch. It seems that there is not so much computational overhead because of CRAM. I will release it after additional tests hopefully next week.

**Comment by willhooper** [comment]
That's great to hear. Thank you for adding this feature!

**Comment by friend1ws** [comment]
We have now pre-released the CRAM-supported version. We will provide a stable release after intensive testing. So I would like to close this issue once.
